apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-depl
  namespace: autoscale
spec:
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:management
          resources:
            limits:
              memory: "256Mi"
              cpu: "1000m"
            requests:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5672
            - containerPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-srv
  namespace: autoscale
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: rabbitmq-dashboard
#   namespace: autoscale
# spec:
#   type: NodePort
#   selector:
#     app: rabbitmq
#   ports:
#     - name: dashboard
#       port: 15672
#       targetPort: 15672
#       nodePort: 30000
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-dashboard-srv
  namespace: autoscale
spec:
  selector:
    app: rabbitmq
  ports:
    - name: dashboard
      port: 15672
      targetPort: 15672
