prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: "kube-state-metrics"
        scrape_interval: 40s
        scrape_timeout: 30s
        static_configs:
          - targets: ["kube-state-metrics.monitoring.svc.cluster.local:8080"]
