- name: Install Docker and Docker Compose
  hosts: all
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name:
          - docker.io
          - docker-compose
        state: present
        update_cache: yes

    - name: Add user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Ensure Docker service is enabled and running
      systemd:
        name: docker
        enabled: yes
        state: started
